// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $api_convert from "./routes/api/convert.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MarkdownConverter from "./islands/MarkdownConverter.tsx";
import * as $RecordDetails from "./islands/RecordDetails.tsx";
import * as $RecordRow from "./islands/RecordRow.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/api/convert.ts": $api_convert,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MarkdownConverter.tsx": $MarkdownConverter,
    "./islands/RecordDetails.tsx": $RecordDetails,
    "./islands/RecordRow.tsx": $RecordRow,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
